name: Build

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install jq
        run: sudo apt-get install -y jq

      - id: getname
        run: |
          echo "NAME=$(cat info.json | jq '.id' | tr -d '"')" >> "$GITHUB_ENV"
          echo "ICON=$(cat info.json | jq '.icon' | tr -d '"')" >> "$GITHUB_ENV"

      - uses: vimtor/action-zip@v1
        with:
          files: info.json ${{ env.ICON }} main.js
          dest: ${{ env.NAME }}.potext

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          name: Release ${{ github.run_id }}
          files: "*.potext"
          token: ${{ secrets.GITHUB_TOKEN }}
