name: Build

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install jq
        run: sudo apt-get install -y jq

      - id: getname
        run: |
          echo "NAME=$(cat info.json | jq '.id' | tr -d '"')" >> "$GITHUB_ENV"
          echo "ICON=$(cat info.json | jq '.icon' | tr -d '"')" >> "$GITHUB_ENV"

      - uses: vimtor/action-zip@v1
        with:
          files: info.json ${{ env.ICON }} main.js
          dest: ${{ env.NAME }}.potext

      - name: Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> "$GITHUB_ENV"

      - name: Generate Version Tag
        id: version
        run: |
          DATE=${{ env.DATE }}
          RUN_NUMBER=$(date +'%H%M%S')
          VERSION="v${DATE}-${GITHUB_RUN_NUMBER}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: "*.potext"
          token: ${{ secrets.GITHUB_TOKEN }}
